# These are supported funding model platforms

ko_fi: redpeacock78
liberapay: redpeacock78
custom:
  [
    "https://www.paypal.me/redpeacock78",
    "https://www.buymeacoffee.com/redpeacock78",
    "https://fantia.jp/fanclubs/218155/plans",
    "https://ofuse.me/redpeacock78",
  ]
